version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - EMAIL_USER=usemeanywhere123@gmail.com
      - EMAIL_PASS=natd jlnw uvjr sefz
      - PORT=5000
    volumes:
      - .:/usr/src/app
